export const MOVIES_MOCK = [
  { 
    MaPhim: "phim-001", 
    TenPhim: "Lật Mặt 7: Một Điều Ước", 
    HinhAnh: "https://image.api.playready.com.vn/api/v2/image/6628b031b268010026e6d338", 
    Rating: 9.8, // Custom field for UI
    Tags: "2D | T16", // Custom field for UI
    NoiDung: "Câu chuyện về tình cảm gia đình đầy xúc động của bà Hai và các con.",
    ThoiLuong: 112,
    TheLoai: "Hành động, Tâm lý",
    NgayKhoiChieu: "2024-04-26",
    NgayKetThuc: "2024-06-26",
    DaoDien: "Lý Hải",
    DienVien: "Trương Minh Cường, Đinh Y Nhung, Quách Ngọc Tuyên",
    GioiHanTuoi: "T16",
    KhaDung: 1
  },
  { 
    MaPhim: "phim-002", 
    TenPhim: "Hành Tinh Khỉ: Vương Quốc Mới", 
    HinhAnh: "https://image.api.playready.com.vn/api/v2/image/66399f668673a500264024c0", 
    Rating: 8.5, 
    Tags: "IMAX | P",
    NoiDung: "Nhiều năm sau triều đại của Caesar, một chú khỉ trẻ bắt đầu một hành trình mới.",
    ThoiLuong: 145,
    TheLoai: "Hành động, Khoa học viễn tưởng",
    NgayKhoiChieu: "2024-05-10",
    NgayKetThuc: "2024-07-10",
    DaoDien: "Wes Ball",
    DienVien: "Owen Teague, Freya Allan, Kevin Durand",
    GioiHanTuoi: "P",
    KhaDung: 1
  },
  { 
    MaPhim: "phim-003", 
    TenPhim: "Dune: Hành Tinh Cát 2", 
    HinhAnh: "https://image.api.playready.com.vn/api/v2/image/65cae9a0397500002636735e", 
    Rating: 9.2, 
    Tags: "3D | T13",
    NoiDung: "Paul Atreides hợp lực với Chani và người Fremen để trả thù những kẻ hủy diệt gia đình mình.",
    ThoiLuong: 166,
    TheLoai: "Hành động, Phiêu lưu",
    NgayKhoiChieu: "2024-03-01",
    NgayKetThuc: "2024-05-01",
    DaoDien: "Denis Villeneuve",
    DienVien: "Timothée Chalamet, Zendaya, Rebecca Ferguson",
    GioiHanTuoi: "T13",
    KhaDung: 1
  },
  { 
    MaPhim: "phim-004", 
    TenPhim: "Kung Fu Panda 4", 
    HinhAnh: "https://image.api.playready.com.vn/api/v2/image/65e96a40879612002660d5b5", 
    Rating: 8.9, 
    Tags: "2D | P",
    NoiDung: "Po được chọn trở thành Thủ lĩnh tinh thần của Thung lũng Hòa bình.",
    ThoiLuong: 94,
    TheLoai: "Hoạt hình, Hành động",
    NgayKhoiChieu: "2024-03-08",
    NgayKetThuc: "2024-05-08",
    DaoDien: "Mike Mitchell",
    DienVien: "Jack Black, Awkwafina, Viola Davis",
    GioiHanTuoi: "P",
    KhaDung: 1
  },
];
